<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class ConfigurationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.,     
     *
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();


        DB::table('configurations')->insert([
            [
                "name"=>"current_session",
                "value"=>'8',                
                "field_type"=>"select",
                "model"=>"App\\Models\\Session",
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name"=>"current_admission_batch",
                "value"=>'1',                
                "field_type"=>"select",
                "model"=>"App\\Models\\AdmissionBatch",
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name"=>"admission_letter_template",
                "value"=>'',                
                "field_type"=>"textarea",           
                "model"=>"",
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],            
            [
                "name"=>"admission_verification_slip_template",
                "value"=>'',                
                "field_type"=>"textarea",           
                "model"=>"",
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],            
            [
                "name"=>"current_application_session",
                "value"=>1,
                "field_type"=>"select",
                "model"=>"App\\Models\\Session",
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
             ],
             [
                "name"=>"entrance_exam_schedule",
                "value"=>"",                
                "field_type"=>"input",   
                "model"=>"",
                "seeds" => "",           
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
             ],
            [ 
                "name" => "grad_min_cgpa",
                "value" => "1.50",                
                "field_type"=>"input",                
                "model"=>"",
                "seeds" => "",  
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "grad_level_id",
                "value" => 4,
                "field_type"=>"select",
                "model"=>"App\\Models\\Level",
                "seeds" => "",  
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "grad_min_credit_units",
                "value" => 10,
                "field_type"=>"input",
                "model"=>"",
                "seeds" => "",  
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "admission_notification_letter_template",
                "value" => "",
                "field_type"=>"textarea",
                "model"=>"",
                "seeds" => "",  
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "admission_acknowledgement_letter_template",
                "value" => "",
                "field_type"=>"textarea",
                "model"=>"",
                "seeds" => "",  
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",

            ],            
            [
                "name" => "application_screening_schedule",
                "value" => "",
                "field_type"=>"input",
                "model"=>"",
                "seeds" => "", 
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "application_notice",
                "value" => "",
                "field_type"=>"textarea",
                "model"=> "",
                "seeds" => "", 
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "students_notice",
                "value" => "",
                "field_type"=>"textarea",
                "model"=>"",
                "seeds" => "", 
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "show_photo_on_receipt",
                "value" => "true",
                "field_type"=>"radio",
                "model"=>"",                
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "show_photo_on_result_slip",
                "value" => "true",
                "field_type"=>"radio",
                "model"=>"",                
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "show_photo_on_olevel_slip",
                "value" => "true",
                "field_type"=>"radio",
                "model"=>"",                
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "show_photo_on_invoice",
                "value" => "true",
                "field_type"=>"radio",
                "model"=>"",
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
                
            ],
            [
                "name" => "show_photo_on_transaction_slip",
                "value" => "true",
                "field_type"=>"radio",
                "model"=>"",                
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "show_photo_on_course_reg",
                "value" => "true",
                "field_type"=>"radio",
                "model"=>"",                
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                "name" => "show_photo_on_exam_card",
                "value" => "true",
                "field_type"=>"radio",
                "model"=>"",                
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name' => "show_photo_on_biodata_slip",
                'value' => 'true',
                "field_type"=>"radio",
                "model"=>"",                
                "seeds" => "true,false",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'application_number_format', 
                'value'=>'COE/{session}/{programme_type}/{number}',
                'field_type'=> 'select',
                "model"=>"",                
                "seeds" => '{school_acronym},{faculty},{department},{entry_mode},{programme_code},{programme_type},{session},{number}',
                "description"=>"",
                "programme_type_id"=>'2',
                "updated_by"=>"",
            ],
            [
                'name'=>'matric_number_format', 
                'value'=>'UG/{session}/{faculty}/{programme}/{number}',
                'field_type'=> 'select',
                "model"=>"",                                
                "seeds" => '{school_acronym},{faculty},{department},{entry_mode},{programme_code},{programme_type},{session},{number}',
                "description"=>"",
                "programme_type_id"=>'2',
                "updated_by"=>"",
            ],
        
            [
                'name'=>'application_number_format', 
                'value'=>'COE/{session}/{programme_type}/{number}',
                'field_type'=> 'select',
                "model"=>"",                
                "seeds" => '{school_acronym},{faculty},{department},{entry_mode},{programme_code},{programme_type},{session},{number}',
                "description"=>"",
                "programme_type_id"=>'1',
                "updated_by"=>"",
            ],
            [
                'name'=>'matric_number_format', 
                'value'=>'UG/{session}/{faculty}/{programme}/{number}',
                'field_type'=> 'select',
                "model"=>"",                                
                "seeds" => '{school_acronym},{faculty},{department},{entry_mode},{programme_code},{programme_type},{session},{number}',
                "description"=>"",
                "programme_type_id"=>'1',
                "updated_by"=>"",
            ],
            [
                'name'=>'allow_course_registration', 
                'value'=>'',
                'field_type'=> 'checkbox',
                "model"=>"App\\Models\\Level",                
                "seeds" => '',
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'allow_payments', 
                'value'=>'',
                'field_type'=> 'checkbox',
                "model"=>"App\\Models\\Level",                
                "seeds" => '',
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],            
            [
                'name'=>'school_state_of_origin', 
                'value'=>10,
                'field_type'=> 'select',
                "model"=>"App\\Models\\State",                
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'current_semester', 
                'value'=>1,
                'field_type'=> 'select',
                "model"=>"App\\Models\\Semester",                
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'final_semester', 
                'value'=>2,
                'field_type'=> 'select',
                "model"=>"App\\Models\\Semester",                
                "seeds" => "",
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'tp_course_setting', 
                'value'=>'13,3',
                'field_type'=> 'dual-data',
                "model"=> "App\\Models\\Level",                
                "seeds" => '',
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ], 
            [
                'name'=>'matric_number_numbering_format', 
                'value'=>'zero_prefix',
                'field_type'=> 'select',
                "model"=> "",                
                "seeds" => 'zero_prefix,level_prefix,session_prefix',
                "description"=>"",
                "programme_type_id"=>'1',
                "updated_by"=>"",
            ],
            [
                'name'=>'matric_number_numbering_format', 
                'value'=>'level_prefix',
                'field_type'=> 'select',
                "model"=> "",                
                "seeds" => 'zero_prefix,level_prefix,session_prefix',
                "description"=>"",
                "programme_type_id"=>'2',
                "updated_by"=>"",
            ],            
            [
                'name'=>'application_number_numbering_format', 
                'value'=>'zero_prefix',
                'field_type'=> 'select',
                "model"=> "",                
                "seeds" => 'zero_prefix,level_prefix,session_prefix',
                "description"=>"",
                "programme_type_id"=>'1',
                "updated_by"=>"",
            ],
            [
                'name'=>'application_number_numbering_format', 
                'value'=>'level_prefix',
                'field_type'=> 'select',
                "model"=> "",                
                "seeds" => 'zero_prefix,level_prefix,session_prefix',
                "description"=>"",
                "programme_type_id"=>'2',
                "updated_by"=>"",
            ],
            [             
                'name' => 'exam_rules',
                'value' => '<h4 style="text-decoration: underline">EXAMINATION RULES AND REGULATIONS </h4>
                <p>1. Candidates should be in vicinity of examination HALL 30 minutes before the examination is due to begin. <br>
                2. Candidates are required to sign the attendance slip on their desk. <br>
                3. No candidates will be permitted <br>
                i. To enter examination hall if he/she is more than 30 minutes late. <br>
                ii. To leave the examination hall before end of 45 minutes after the commencement of the examination. <br>
                iii. To leave the examination hall during the last 15 minutes of the exam. <br>
                4. Candidates must sit at desk with number corresponding to those on their admission card. They are not permitted to move their
                desk. <br>
                5. If a student needs anything, the Invigilator should be called upon by the student by raising up his/her hand. <br>
                6. Candidates are not permitted to introduce into the examination hall papers of any kind violation of this rule attract out right
                dismissal. <br>
                7. Candidate must write their examination number only on each separate answer book and on each supplementary sheet used under
                no circumstance must they write their names. <br>
                8. If they wish to attract the attention of the invigilator they should raise their hands. <br>
                9. No smoking No chewing and No Girafffing. <br>
                10. Candidates must not jot down any points or write on the examination cards or question paper. <br>
                11. Communication of any kinds is strickly forbidden. <br>
                12. Candidates must not enter the examination hall with handset or any computerized gadget </p>',
                'field_type'=> 'textarea',
                'model'=> '',
                "seeds" => '',
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name' => 'disable_ca_score_upload',
                'value' => '',
                'field_type'=> 'checkbox',
                'model'=> 'App\\Models\\Course',
                "seeds" => '',
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name' => 'disable_exam_score_upload',
                'value' => '',
                'field_type'=> 'checkbox',
                'model'=> 'App\\Models\\Course',
                "seeds" => '',
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'allow_alevel_edit', 
                'value'=>'',
                'field_type'=> 'select',
                "model"=> "App\\Models\\ProgrammeType",                
                "seeds" => '',    
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",            
            ],
            [
                'name'=>'allow_olevel_edit', 
                'value'=>'',
                'field_type'=> 'select',
                "model"=> "App\\Models\\ProgrammeType",                
                "seeds" => '',  
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",              
            ],
            [
                'name'=>'allow_profile_edit', 
                'value'=>'',
                'field_type'=> 'select',
                "model"=> "App\\Models\\ProgrammeType",                
                "seeds" => '',                
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'required_jamb_for_application', 
                'value'=>"false",
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => "true,false",    
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",            
            ],            
            [
                'name'=>'allow_print_admission_letter', 
                'value'=>"false",
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => "true,false",   
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",             
            ],
            [
                'name'=>'allow_print_notification_letter', 
                'value'=>"false",
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => "true,false",   
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",             
            ],        
            [
                'name'=>'allow_print_acknowledgement_letter', 
                'value'=>"false",
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => "true,false",      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ],            
            [
                "name" => "require_level_for_application",
                "value" => 1,
                "field_type"=>"select",
                "model"=>"App\\Models\\Level",
                "seeds" => "",  
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'active_programme_types', 
                'value'=>'2',
                'field_type'=> 'checkbox',
                "model"=> "App\\Models\\ProgrammeType",                
                "seeds" => '',    
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",            
            ],
            [
                'name'=>'applicant_registration', 
                'value'=>'true',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'true,false',                
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",
            ],
            [
                'name'=>'display_application_notice', 
                'value'=>'true',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'true,false',   
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",             
            ],
            [
                'name'=>'display_students_notice', 
                'value'=>'true',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'true,false',      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ],
            [
                'name'=>'enable_theme_string', 
                'value'=>'true',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'true,false',      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ],    
            [
                'name'=>'enable_programme_type', 
                'value'=>'false',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'default,false',      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ],    
            [
                'name'=>'default_password', 
                'value'=>'0000',
                'field_type'=> 'text',
                "model"=> "",                
                "seeds" => '',      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ],    
            [
                'name'=>'enable_faculty', 
                'value'=>'false',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'default,false',      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ],    
            [
                'name'=>'enable_department', 
                'value'=>'false',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'default,false',      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ],    
            [
                'name'=>'enable_entry_mode', 
                'value'=>'false',
                'field_type'=> 'radio',
                "model"=> "",                
                "seeds" => 'default,false',      
                "description"=>"",
                "programme_type_id"=>'',
                "updated_by"=>"",          
            ]
        ]);
    }
}
